apiVersion: apps/v1 
kind: Deployment
metadata:
  name: dogs-api
spec:
  selector:
    matchLabels:
      app: dogs-api
  template:
    metadata:
      labels:
        app: dogs-api
    spec:
      containers:
      - name: dogs-api
        image: kimschles/node-to-helm:latest
        command: ["npm", "start"]
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "64Mi"
            cpu: "70m"
          limits:
            memory: "64Mi"
            cpu: "70m"